[hooks]
webhook_gen = "https://discord.com/api/webhooks/1184508491986116709/e5dBf-lXKY7dwWJsUTUdN6D6uhJEZsIdK-SyMkgS1u2L6RBUmwh6t7p6r4_zn0u3WZKQ"
webhook_log = "https://discord.com/api/webhooks/1184509050772263012/a4tM0ML5zQdq4cxlLsj3tXN1NfMWo0dyirtVriKAikS8NAKjiWV9w0sEOCjbJnox36ZS"
webhook_HPC = "https://discord.com/api/webhooks/1184518192203321416/wbv1TvZ51JHDB3zgUe9Y6RfFZqOlNxYI2fmEokUAB6K0ZJ8-XEpBlEjnIhf5-aL8joCs"